In [1]:
!pip install pandas
!pip install numpy
!pip install tensorflow

Requirement already satisfied: pandas in ./Jupyter_lab/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in ./Jupyter_lab/lib/python3.12/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./Jupyter_lab/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./Jupyter_lab/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in ./Jupyter_lab/lib/python3.12/site-packages (2.4.2)
Requirement already satisfied: tensorflow in ./Jupyter_lab/lib/python3.12/site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (7.34.0)
Requirement already satisfied: requests<3,>=2.21.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (82.0.0)
Requirement already satisfied: six>=1.12.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (2.4.2)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in ./Jupyter_lab/lib/python3.12/site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in ./Jupyter_lab/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./Jupyter_lab/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./Jupyter_lab/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./Jupyter_lab/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./Jupyter_lab/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in ./Jupyter_lab/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow) (14.3.3)
Requirement already satisfied: namex in ./Jupyter_lab/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in ./Jupyter_lab/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./Jupyter_lab/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./Jupyter_lab/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in ./Jupyter_lab/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1773011548.838586   53785 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1773011548.885543   53785 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1773011550.221305   53785 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [3]:
a11=np.random.random(62500)*40-20
a12=np.random.random(62500)*40-20
a21=np.random.random(62500)*40-20
a22=np.random.random(62500)*40-20

b11=np.random.random(62500)*40-20
b12=np.random.random(62500)*40-20
b21=np.random.random(62500)*40-20
b22=np.random.random(62500)*40-20


df=pd.DataFrame({   'a11':a11,
                    'a12':a12,
                    'a21':a21,
                    'a22':a22,
                    'b11':b11,
                    'b12':b12,
                    'b21':b21,
                    'b22':b22,
                    })

print(len(df),len(df.drop_duplicates()))

df['R11']=(df['a11']*df['b11'])+(df['a12']*df['b21'])
df['R12']=(df['a11']*df['b12'])+(df['a12']*df['b22'])
df['R21']=(df['a21']*df['b11'])+(df['a22']*df['b21'])
df['R22']=(df['a21']*df['b12'])+(df['a22']*df['b22'])

df.head()

62500 62500

,a11,a12,a21,a22,b11,b12,b21,b22,R11,R12,R21,R22
0,14.823633,12.332931,-18.398789,10.386570,5.425406,11.267611,-17.110112,-11.853501,-130.593592,20.838521,-277.536280,-330.427615
1,-9.050358,11.558370,12.907410,6.671741,-1.764702,-17.480763,-9.846945,18.640205,-97.843447,373.657544,-88.474000,-101.268772
2,-17.956662,-17.088940,15.643419,12.822743,-3.868456,3.212940,-0.043583,6.282605,70.209346,-165.056737,-61.074734,130.821594
3,-11.758617,0.206207,15.915820,7.914989,-5.808730,13.859880,14.496768,3.106092,71.291971,-162.332525,22.291061,245.176047
4,0.006651,5.925254,-9.105407,-3.134909,-9.803840,0.639161,4.176481,17.845394,24.681511,105.742743,76.175064,-61.763501

In [4]:
df_train=df[:50000]
df_test=df[50000:]

print(len(df_train), len(df_test))

50000 12500

In [5]:
print(df.columns)

Index(['a11', 'a12', 'a21', 'a22', 'b11', 'b12', 'b21', 'b22', 'R11', 'R12',
       'R21', 'R22'],
      dtype='str')

In [6]:
salidas=['R11','R12','R21','R22']
entradas=['a11', 'a12', 'a21', 'a22', 'b11', 'b12', 'b21', 'b22']
tamaño=len(entradas)

x=[]

for i in entradas:
    x.append(df_train[i])

X=np.column_stack(x)

y=[]

for i in salidas:
    y.append(df_train[i])

Y=np.column_stack(y)

entrada = tf.keras.layers.Dense(units=tamaño, input_shape=[tamaño], activation="relu")
c1 = tf.keras.layers.Dense(units=128, activation="relu")
c2 = tf.keras.layers.Dense(units=128, activation="relu")
c3 = tf.keras.layers.Dense(units=128, activation="relu")
salida = tf.keras.layers.Dense(units=4, activation="linear")
red = tf.keras.Sequential([entrada, c1, c2, salida])
#red = tf.keras.Sequential([entrada, c1, c2,c3,c4, c5,c6, salida])
red.compile(optimizer='adam',
            loss="mse",
            metrics=['accuracy'])

/home/robotica/Jupyter_lab/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1773011552.249844   53785 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

In [7]:
historial = red.fit(X, Y, epochs=500, verbose=False)

In [ ]:
def clasificar_dataframe(df, modelo, columnas, salidas):
    X = df[columnas].values
    preds = modelo.predict(X)

    for i in range(len(salidas)):
        df[salidas[i]] = preds[:,i]
#    df['R11_a'] = preds[:,0]
    #df['Predeccion']=(preds > 0.5).astype(int)
    return df

salidas_2 = []
errores= []
for i in salidas:
    salidas_2.append(f'{i}_pred')
    errores.append(f'{i}_error')

clasificar_dataframe(df_test, red, entradas, salidas_2)

391/391 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step

,a11,a12,a21,a22,b11,b12,b21,b22,R11,R12,R21,R22,R11_pred,R12_pred,R21_pred,R22_pred
50000,-10.296425,-16.269695,-11.134132,-16.911809,17.157695,-4.347177,16.513619,-12.578158,-445.334448,249.403177,-470.311200,261.121448,-457.202576,253.164154,-470.168945,265.480347
50001,-18.802763,-11.831320,-5.506835,-11.807522,13.249027,-1.524830,-6.659585,7.142879,-170.326624,-55.838673,5.672988,-75.942714,-170.501541,-55.422577,11.511721,-72.553711
50002,1.254182,15.613391,6.710497,-18.479639,6.164422,16.515157,5.620267,-3.079959,95.482728,-27.375588,-62.494160,167.741448,89.097206,-31.438814,-54.773144,168.938538
50003,7.003838,19.884678,-8.982899,15.441318,2.073978,6.859388,-6.084258,6.799289,-106.457710,183.243713,-112.579304,43.372789,-120.154640,179.928528,-114.976654,44.539490
50004,0.532905,2.122204,15.310877,-10.791114,-14.638088,-11.166432,-16.077932,15.291498,-41.921376,26.501031,-50.623173,-335.980172,-54.253853,22.650709,-54.647175,-321.974335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62495,16.452364,3.564549,-16.411788,3.980834,1.163320,18.996751,-4.151206,10.044708,4.342193,348.346312,-35.617432,-271.784347,-7.925302,349.181763,-31.825163,-276.846954
62496,-7.781946,8.954133,13.607717,-8.039546,-0.877521,10.283760,0.695623,18.804318,13.057524,88.348695,-17.533555,-11.239670,7.718307,79.295013,-15.273283,-7.656675
62497,-5.223015,-6.390902,-9.016899,-11.069522,-14.214023,-16.171646,-5.667530,3.800189,110.460682,60.178121,190.903250,103.751827,114.755043,57.699234,197.952499,107.614319
62498,-6.981147,-7.726787,18.707166,-6.997274,0.933717,16.828897,14.719697,15.027361,-120.254384,-233.598229,-85.530563,209.670399,-124.735313,-239.448364,-77.542961,215.318130
62499,-13.016681,-14.290697,7.596648,-2.019565,8.010070,-8.906018,5.458529,-14.302036,-182.270708,320.312853,49.825832,-38.771999,-182.675446,323.118256,57.376865,-37.226830

In [ ]:
df_test_

In [22]:

errores= []
for i in salidas:
    salidas_2.append(f'{i}_pred')
    errores.append(f'{i}_error')

for i in zip(salidas, salidas_2, errores):
    df_test[i[2]]=np.abs((df_test[i[0]]-df_test[i[1]])/df_test[i[0]])*100
    print(i)

df_test['error_media'] = df_test[errores].mean(axis=1)

df_test.head(50)

('R11', 'R11_pred', 'R11_error')
('R12', 'R12_pred', 'R12_error')
('R21', 'R21_pred', 'R21_error')
('R22', 'R22_pred', 'R22_error')

,a11,a12,a21,a22,b11,b12,b21,b22,R11,R12,...,R22,R11_pred,R12_pred,R21_pred,R22_pred,R11_error,R12_error,R21_error,R22_error,error_media
50000,-10.296425,-16.269695,-11.134132,-16.911809,17.157695,-4.347177,16.513619,-12.578158,-445.334448,249.403177,...,261.121448,-457.202576,253.164154,-470.168945,265.480347,2.664992,1.507991,0.030247,1.669299,1.468132
50001,-18.802763,-11.831320,-5.506835,-11.807522,13.249027,-1.524830,-6.659585,7.142879,-170.326624,-55.838673,...,-75.942714,-170.501541,-55.422577,11.511721,-72.553711,0.102695,0.745176,102.921640,4.462578,27.058022
50002,1.254182,15.613391,6.710497,-18.479639,6.164422,16.515157,5.620267,-3.079959,95.482728,-27.375588,...,167.741448,89.097206,-31.438814,-54.773144,168.938538,6.687620,14.842514,12.354780,0.713652,8.649642
50003,7.003838,19.884678,-8.982899,15.441318,2.073978,6.859388,-6.084258,6.799289,-106.457710,183.243713,...,43.372789,-120.154640,179.928528,-114.976654,44.539490,12.866076,1.809167,2.129476,2.689936,4.873664
50004,0.532905,2.122204,15.310877,-10.791114,-14.638088,-11.166432,-16.077932,15.291498,-41.921376,26.501031,...,-335.980172,-54.253853,22.650709,-54.647175,-321.974335,29.418112,14.528952,7.948932,4.168650,14.016161
50005,6.422542,-3.402325,-3.891404,6.567962,1.717307,-7.989230,-4.616258,-4.697179,26.735484,-35.329834,...,0.238428,22.076748,-36.669319,-36.269703,-1.671103,17.425291,3.791371,1.979448,800.883404,206.019879
50006,-1.073654,10.336212,10.511335,14.611446,-1.071100,5.076497,-11.013083,15.705734,-112.683572,156.887391,...,282.844232,-121.134819,157.288025,-178.154388,285.591431,7.499982,0.255364,3.472397,0.971276,3.049755
50007,19.767422,-7.142131,-1.989368,-1.883004,9.057282,-0.984606,-15.644792,-16.832062,290.776278,100.753671,...,33.653578,285.375885,102.770340,8.887758,38.131981,1.857233,2.001583,22.316161,13.307361,9.870585
50008,16.645617,-13.833755,19.374661,5.335015,15.456123,1.039224,-3.501191,-11.957636,305.711327,182.717530,...,-43.659549,306.592468,184.072296,285.759613,-43.874332,0.288227,0.741454,1.774130,0.491951,0.823940
50009,-8.676622,12.327230,-0.000014,-8.798785,9.089902,11.995731,15.472948,19.710406,111.868933,138.892272,...,-173.427799,106.783081,132.799423,-123.919640,-172.964294,4.546259,4.386744,8.978509,0.267261,4.544693
50010,-2.791488,5.062354,17.887042,13.717689,6.063177,-17.272703,9.994666,-1.854479,33.671247,38.828518,...,-334.396738,31.658562,39.563168,244.110092,-332.871674,5.977459,1.892036,0.588841,0.456065,2.228600
50011,14.283434,2.625102,5.749778,-4.626374,0.923065,-16.408253,-17.558977,4.557761,-32.909574,-222.401601,...,-115.429712,-43.356560,-220.492737,83.056190,-112.281136,31.744517,0.858296,4.027667,2.727700,9.839545
50012,-13.837229,18.629068,7.588171,-5.998893,16.188178,-3.144089,-17.033854,13.437101,-541.324350,293.826152,...,-104.465613,-543.349487,282.526245,231.640350,-96.936462,0.374108,3.845780,2.940781,7.207301,3.591992
50013,15.271776,-12.895003,17.039546,-8.433886,9.831707,4.319239,2.596487,-5.010777,116.665914,130.576438,...,115.858192,107.824066,132.699219,151.271469,121.867958,7.578775,1.625699,3.874309,5.187174,4.566489
50014,4.732600,-16.949220,5.521279,6.098960,-2.664690,-15.747972,-14.663193,9.991096,235.918782,-243.870132,...,-26.013648,234.488525,-239.903793,-107.293564,-26.328730,0.606250,1.626414,3.025508,1.211215,1.617347
50015,-12.530528,-9.476178,-17.962534,18.705958,14.679649,-19.813028,18.835996,6.396176,-362.437008,187.656401,...,475.538791,-362.159851,180.169510,89.207321,475.292908,0.076470,3.989681,0.615447,0.051706,1.183326
50016,-18.890423,-3.157333,-3.839192,4.597322,-11.087819,17.155247,-3.041194,10.829300,219.055656,-358.261586,...,-16.076521,224.259827,-369.130493,27.853970,-16.757063,2.375730,3.033791,2.563944,4.233140,3.051651
50017,-14.999080,-17.449758,16.936398,11.726031,10.837380,0.609249,-13.864918,-11.917578,79.388742,198.820668,...,-129.427401,74.959816,200.777878,20.381395,-131.758636,5.578784,0.984410,2.786990,1.801192,2.787844
50018,-8.957870,1.329073,13.651885,13.037254,-6.511734,8.513260,-8.234303,-4.705907,47.387278,-82.515175,...,54.869944,39.023666,-86.062897,-206.378571,57.028366,17.649488,4.299478,5.160975,3.933706,7.760912
50019,16.520020,-14.582540,-10.613311,-6.721475,19.548440,-18.646710,9.079356,8.883128,190.540544,-437.582594,...,138.195603,192.098984,-441.740051,-262.702301,144.513107,0.817905,0.950097,2.159413,4.571422,2.124709
50020,15.669105,2.046914,14.808131,-15.258475,-9.757250,19.847014,14.059709,-16.440225,-124.108352,277.333209,...,544.749955,-122.362022,264.486816,-357.450439,543.670898,1.407101,4.632115,0.436168,0.198083,1.668367
50021,19.934009,-19.042375,-10.046969,15.848265,16.846147,-10.809707,8.689815,-7.013225,170.336509,-81.932332,...,-2.542656,165.034561,-82.029839,-25.418516,-1.652220,3.112631,0.119009,19.393858,35.019911,14.411352
50022,-9.727147,-12.943354,-18.995381,-10.154018,-9.441154,19.783422,-3.959326,-8.753030,143.082447,-79.142685,...,-286.915205,146.955963,-84.894516,223.417923,-277.525452,2.707192,7.267673,1.765745,3.272658,3.753317
50023,18.877153,1.923313,13.399239,-7.279712,-7.855392,-4.512174,11.986019,-1.397709,-125.234568,-87.865230,...,-50.284774,-123.874138,-87.745697,-185.254364,-51.955540,1.086306,0.136041,3.769481,3.322607,2.078609
50024,7.972347,16.611629,-14.262085,12.751047,-19.651865,-4.509260,12.774479,-11.014850,55.533418,-218.923980,...,-76.139425,45.860092,-217.338272,449.028534,-73.120712,17.418927,0.724319,1.323209,3.964716,5.857793
50025,-15.057461,-14.221300,-17.600416,11.041863,-17.929998,-1.656272,-9.189833,9.721446,400.671610,-113.312349,...,136.493955,406.207275,-118.459267,215.029312,132.452499,1.381597,4.542239,0.432859,2.960905,2.329400
50026,-14.338844,6.067093,7.893271,-8.836722,16.559882,15.610187,15.560076,0.774199,-143.045123,-219.134899,...,116.374056,-150.981705,-229.342453,1.907610,119.091629,5.548307,4.658114,128.100884,2.335205,35.160628
50027,-11.179921,-17.378454,6.920960,-19.394686,4.515540,-9.159569,6.835307,-12.766396,-169.270440,324.263494,...,184.207233,-171.297852,322.949768,-90.321106,178.853973,1.197735,0.405142,10.852744,2.906107,3.840432
50028,14.070587,-7.744553,-2.805528,-2.832643,-13.244739,15.506367,-15.962969,-16.815391,-62.735192,348.411356,...,4.128454,-63.831306,341.476227,79.584686,2.270685,1.747208,1.990500,3.388366,44.999141,13.031304
50029,-1.807828,3.626842,-1.495985,-6.323164,11.624991,-7.244043,-2.689140,-13.067120,-30.769074,-34.296386,...,93.462520,-29.733261,-34.419209,0.237086,94.451126,3.366410,0.358120,161.272902,1.057756,41.513797
50030,-12.079110,-0.297069,-1.023233,12.821327,-9.051990,19.111325,-11.517332,-12.667862,112.761423,-227.084561,...,-181.974132,111.151344,-240.783447,-143.100632,-184.961029,1.427863,6.032504,3.392539,1.641385,3.123573
50031,-9.363773,-12.791985,12.475457,9.378855,16.864636,3.768484,-6.208525,-12.718121,-78.497271,127.402793,...,-72.267855,-82.380783,125.347824,160.089951,-71.516296,4.947321,1.612970,5.208001,1.039963,3.202064
50032,7.376164,14.412157,1.080581,19.410127,5.381197,11.210298,15.676162,2.486533,265.619905,118.525303,...,60.377558,260.088837,116.788116,317.996277,65.221634,2.082324,1.465668,2.549303,8.022974,3.530067
50033,-3.817566,-5.533073,8.263014,-19.382996,6.404139,0.369156,-5.865477,-10.346746,8.005889,55.840031,...,203.601285,4.772502,56.903366,169.403091,208.926895,40.387605,1.904253,1.677641,2.615706,11.646301
50034,18.329661,-3.069613,12.766338,11.598768,2.351393,8.978388,-12.503638,10.240229,81.481572,133.137273,...,233.395192,73.419701,147.694717,-122.003029,234.491089,9.894104,10.934161,6.082106,0.469546,6.844979
50035,-9.876249,14.653959,-1.356536,0.909550,-12.003148,15.476181,12.929623,4.190567,308.016251,-91.438210,...,-17.182465,306.869904,-99.271049,37.049789,-16.582464,0.372171,8.566265,32.118509,3.491939,11.137221
50036,-11.542549,5.702843,-18.084238,-1.134440,-9.638283,-9.290127,6.502037,11.272786,148.330449,171.518678,...,155.216561,143.268692,165.508392,170.537827,159.761795,3.412487,3.504158,2.164449,2.928317,3.002353
50037,5.246798,-14.834666,-15.371799,-11.898613,17.214917,-9.383871,-5.655062,-12.902880,174.214141,142.174629,...,297.773344,172.020279,145.054230,-198.648666,299.334778,1.259290,2.025397,0.664755,0.524370,1.118453
50038,16.936719,3.600194,-18.060964,8.036156,18.415849,8.018204,19.417531,1.984711,381.810929,142.947408,...,-128.867044,376.199554,146.293228,-174.468384,-128.700882,1.469674,2.340595,1.187831,0.128941,1.281760
50039,-7.384323,-5.151011,-9.892971,6.393961,11.043877,-17.701390,16.658348,6.259639,-167.358882,98.469314,...,215.143221,-171.187683,88.678307,-0.361616,215.938522,2.287779,9.943206,86.821237,0.369661,24.855471
50040,13.091315,10.440265,5.128965,19.902638,17.556928,-13.446213,-12.193930,-10.664312,102.535423,-287.366858,...,-281.213094,95.013145,-291.135315,-157.099838,-292.285004,7.336272,1.311375,2.920118,3.937195,3.876240
50041,-12.828228,1.250585,-13.357199,13.130471,17.227961,12.987981,-10.536155,-3.380978,-234.180575,-170.840978,...,-217.876875,-241.393997,-173.510223,-369.252960,-219.547607,3.080282,1.562415,0.214668,0.766824,1.406047
50042,2.577299,10.774679,-19.956632,-16.655895,17.089500,10.401347,9.410047,-6.999573,145.434993,-48.610776,...,-90.991694,147.335114,-53.064953,-485.718964,-87.829773,1.306509,9.162940,2.423282,3.474955,4.091922
50043,2.859895,0.893364,-18.835993,-1.110948,-7.866280,-17.314726,18.420216,15.970940,-6.040770,-35.250434,...,308.397182,-12.198560,-39.219917,136.020065,309.489197,101.937154,11.260806,6.510905,0.354094,30.015740
50044,15.166958,-12.914769,14.836132,-13.146789,2.348995,-5.730006,-8.769120,19.073936,148.878265,-333.242228,...,-335.772132,142.765686,-322.619293,158.273056,-331.850952,4.105757,3.187752,5.419952,1.167810,3.470317
50045,-18.875748,7.444832,-19.617168,15.049433,5.070776,19.677671,14.831633,3.433847,14.704334,-345.866342,...,-334.342726,5.227317,-353.261841,132.644760,-324.446777,64.450501,2.138253,7.202061,2.959822,19.187659
50046,12.326229,15.594206,2.857718,15.714181,5.996661,9.465389,-11.300381,-18.705215,-102.304246,-175.020424,...,-266.887723,-117.569901,-179.808197,-164.996002,-272.362030,14.921820,2.735551,2.840039,2.051165,5.637143
50047,10.349346,-14.822998,-1.248612,-0.894688,-6.275878,-19.463103,13.079784,13.392306,-258.832853,-399.944518,...,12.319929,-259.429260,-405.644775,0.343813,19.954237,0.230422,1.425262,108.892822,61.967143,43.128912
50048,15.532641,-19.617933,-14.109818,-15.424926,-10.595471,-16.314717,14.038678,19.573686,-439.985499,-637.405901,...,-71.724959,-437.926208,-637.393066,-56.921650,-53.565384,0.468036,0.002014,15.099823,25.318348,10.222055
50049,10.709518,-13.912534,-2.028351,15.229896,-6.046889,-19.605614,-18.771431,13.613383,196.398908,-399.363321,...,247.097479,192.709717,-404.185181,-281.541718,244.668747,1.878417,1.207387,2.894499,0.982904,1.740802